{% set version = "0.8.1" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 57128ff329a6646651a234a3567bf1a40411005d94e466f2c3b21e2216ab8579

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - panel = panel.cli:main

requirements:
  host:
    - python
    - pip
    # These are also needed at build time.
    - pyct >=0.4.4
    - nodejs >=9.11.1
    - bokeh >=1.4.0,<2.0
  run:
    - python
    - bokeh >=1.4.0,<2.0
    - param >=1.9.2
    - pyviz_comms >=0.7.3
    - markdown
    - pyct >=0.4.4
    - tqdm

test:
  imports:
    - panel
    - panel.io
  commands:
    - pip check
    - panel --help
  requires:
    - pip

about:
  home: https://panel.holoviz.org
  summary: A high-level app and dashboarding solution for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
