travis:
  secure:
    BINSTAR_TOKEN: kZ0YtwkaK9eunL8r/c6bT1DkwTjHvK7sUciLxtJDGtpzlg0N4GKvfX+DfTNRXAEb+6pGH9oa2puM6wG07O/eyffkEWyKEKs3G6KBECp/KjAk0gJPrILCchStKS6KCbmoBCPME6Sk42nxrTiL5m98j119ox5lkDBnZrqi0uA50yOApC+JyGrLp6HbMHs3i0j4D08kMHy90p3ZoYGktKt8d3J504COQIN/TOYxl6kScytRhfufPIwEwPFHoSkK/oU11d6y94lnNjsklpA5RmwYGgPDXGVxlQI2Dbvb1HToK4SGjS+bJ4PSsH9JiMUR2N+4jcD5XpvCVY017d1WVN9bML67kE7Rh0cYnJOsQFrTlncFGbAdhhsuSxXKiv1+KzO9a4BFl4TJCBcn9MBuVW5fnULexBQ74XBaMszgNOO0K/wAzUHZHQ0E+hL33fMxc1dcqzYiGGTbtZsmVXo6qvVwc2cGoS7W19YAIvoiKT6zpx6XEwGPkzkrmCfbJdk6okU80C3KJyOtOw40N4/NCbx+BzNOz700sqVtCvBQtaRXb2TOeRAq06p3hq2/NrPlX1HauDcOFnN+1xk4WwAt8w/eP/LfRuy9kvkSbUYztTUNuXGXlbOpyLQlTZ8N28HYPMnKG2GCSsYhL2XBm7DMrg21WCg+BBQ7c7ivuxUhd5KGtcA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
